repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: poetry run black app
        files: '^.*\.py$'
        language: system
      - id: system
        name: flake8
        entry: poetry run flake8
        files: '^.*\.py$'
        args: [ '--max-line-length=120', '--ignore=E501,W503' ]
        language: system
      - id: system
        name: isort
        entry: poetry run isort app
        files: '^.*\.py$'
        language: system
      - id: system
        name: mypy
        entry: poetry run mypy app
        pass_filenames: false
        language: system
      - id: import-linter
        name: import-linter
        entry: poetry run lint-imports
        pass_filenames: false
        language: system
