version: '3.9'

services:
    url-shortener-app:
        build:
            context: .
        volumes: ['./app:/opt/app']
        ports:
            - "5001:5000"
        environment:
            APP_PORT: 5000
            APP_HOT_RELOAD: 1
            REDIS_HOST: url-shortener-redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: MDNcVb924a
        depends_on:
            - url-shortener-redis
    url-shortener-nginx:
        image: nginx:1.23-alpine
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - "80:80"
        depends_on:
            - url-shortener-app
    url-shortener-redis:
        image: redis:7.0-alpine
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --requirepass MDNcVb924a --
