apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
        - name: url-shortener-nginx
          image: nginx:1.23-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: url-shortener-app
          image: url-shortener-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: APP_PORT
              value: "5001"
            - name: REDIS_HOST
              value: url-shortener-redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: MDNcVb924a
        - name: url-shortener-redis
          image: redis:7.0-alpine
          imagePullPolicy: IfNotPresent
          command: ["redis-server", "--save", "60", "1", "--requirepass", "MDNcVb924a", "--"]
          ports:
            - containerPort: 6379